//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHSForm.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ID { get; set; }
        public string ISO { get; set; }
        public string CountryName { get; set; }
        public string CountryNicename { get; set; }
        public string ISO3 { get; set; }
        public Nullable<short> Numcode { get; set; }
        public int Phonecode { get; set; }
    }
}
