//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHSForm.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CustomerCarServiceDetails = new HashSet<CustomerCarServiceDetail>();
            this.CustomerComplaints = new HashSet<CustomerComplaint>();
            this.CustomerCustomDateTimes = new HashSet<CustomerCustomDateTime>();
            this.CustomerFeedbacks = new HashSet<CustomerFeedback>();
            this.CustomerInovices = new HashSet<CustomerInovice>();
            this.CustomerTransactions = new HashSet<CustomerTransaction>();
            this.StaffCustomerRatings = new HashSet<StaffCustomerRating>();
            this.CustomerAvailabilities = new HashSet<CustomerAvailability>();
            this.CustomerDateBlocks = new HashSet<CustomerDateBlock>();
            this.CustomerOfficalDetails = new HashSet<CustomerOfficalDetail>();
            this.CustomerOtherProperties = new HashSet<CustomerOtherProperty>();
            this.CustomerPricings = new HashSet<CustomerPricing>();
            this.CustomerSpecializedCleanings = new HashSet<CustomerSpecializedCleaning>();
            this.CustomerTimelines = new HashSet<CustomerTimeline>();
            this.Files = new HashSet<File>();
            this.Properties = new HashSet<Property>();
            this.CustomerSupports = new HashSet<CustomerSupport>();
            this.CustomerAlerts = new HashSet<CustomerAlert>();
        }
    
        public int cuID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string AlternativeNo { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Landmark { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> Pincode { get; set; }
        public Nullable<int> PhoneCode { get; set; }
        public string IdentityProveName { get; set; }
        public string IdentityProveID { get; set; }
        public Nullable<int> uID { get; set; }
        public Nullable<int> suID { get; set; }
        public Nullable<int> logID { get; set; }
        public Nullable<int> CreatedRole { get; set; }
        public Nullable<int> UpdatedRole { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Salutaion { get; set; }
        public string WhatsAppNo { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<bool> IsEmail { get; set; }
        public Nullable<System.DateTime> CustomerTypeOn { get; set; }
    
        public virtual Admin_Sub Admin_Sub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCarServiceDetail> CustomerCarServiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerComplaint> CustomerComplaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCustomDateTime> CustomerCustomDateTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerFeedback> CustomerFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerInovice> CustomerInovices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTransaction> CustomerTransactions { get; set; }
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffCustomerRating> StaffCustomerRatings { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAvailability> CustomerAvailabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDateBlock> CustomerDateBlocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOfficalDetail> CustomerOfficalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOtherProperty> CustomerOtherProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPricing> CustomerPricings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSpecializedCleaning> CustomerSpecializedCleanings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTimeline> CustomerTimelines { get; set; }
        public virtual CustomerType CustomerType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSupport> CustomerSupports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAlert> CustomerAlerts { get; set; }
    }
}
