//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHSForm.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOfficalDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerOfficalDetail()
        {
            this.CustomerAvailabilities = new HashSet<CustomerAvailability>();
            this.CustomerCarServiceDetails = new HashSet<CustomerCarServiceDetail>();
            this.CustomerComplaints = new HashSet<CustomerComplaint>();
            this.CustomerCustomDateTimes = new HashSet<CustomerCustomDateTime>();
            this.CustomerDateBlocks = new HashSet<CustomerDateBlock>();
            this.CustomerFeedbacks = new HashSet<CustomerFeedback>();
            this.CustomerInovices = new HashSet<CustomerInovice>();
            this.CustomerTransactions = new HashSet<CustomerTransaction>();
            this.StaffCustomerRatings = new HashSet<StaffCustomerRating>();
            this.CustomerOtherProperties = new HashSet<CustomerOtherProperty>();
            this.CustomerPricings = new HashSet<CustomerPricing>();
            this.CustomerSpecializedCleanings = new HashSet<CustomerSpecializedCleaning>();
            this.CustomerTimelines = new HashSet<CustomerTimeline>();
            this.Files = new HashSet<File>();
        }
    
        public int custODID { get; set; }
        public Nullable<int> custID { get; set; }
        public Nullable<int> catID { get; set; }
        public Nullable<int> catsubID { get; set; }
        public Nullable<bool> SpecialService { get; set; }
        public Nullable<int> propaID { get; set; }
        public Nullable<int> propType { get; set; }
        public Nullable<int> vID { get; set; }
        public Nullable<int> proprestID { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> CreatedRole { get; set; }
        public Nullable<int> UpdatedRole { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string AppartmentNumber { get; set; }
        public Nullable<int> stfID { get; set; }
        public Nullable<int> teamID { get; set; }
        public Nullable<int> StatusOfWork { get; set; }
        public Nullable<int> TaskNo { get; set; }
        public string ClosingRemarks { get; set; }
        public string BuldleDays { get; set; }
        public Nullable<bool> ServiceStatus { get; set; }
        public Nullable<int> NoOfMonths { get; set; }
        public Nullable<int> cartID { get; set; }
        public Nullable<int> carstID { get; set; }
        public Nullable<bool> IsCarWash { get; set; }
        public Nullable<int> subAreaID { get; set; }
        public Nullable<int> carTRID { get; set; }
    
        public virtual CarServiceType CarServiceType { get; set; }
        public virtual CarType CarType { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAvailability> CustomerAvailabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCarServiceDetail> CustomerCarServiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerComplaint> CustomerComplaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCustomDateTime> CustomerCustomDateTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDateBlock> CustomerDateBlocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerFeedback> CustomerFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerInovice> CustomerInovices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTransaction> CustomerTransactions { get; set; }
        public virtual MainCategory MainCategory { get; set; }
        public virtual PropertyArea PropertyArea { get; set; }
        public virtual PropertyResidenceType PropertyResidenceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffCustomerRating> StaffCustomerRatings { get; set; }
        public virtual SubArea SubArea { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Venture Venture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOtherProperty> CustomerOtherProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPricing> CustomerPricings { get; set; }
        public virtual CustomerRenewalMonth CustomerRenewalMonth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSpecializedCleaning> CustomerSpecializedCleanings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTimeline> CustomerTimelines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Team Team { get; set; }
        public virtual CarWashTimeRange CarWashTimeRange { get; set; }
    }
}
