//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHSForm.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTimeBlock
    {
        public int custTBID { get; set; }
        public Nullable<int> TempID { get; set; }
        public string Days { get; set; }
        public string Times { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> teamID { get; set; }
        public string MobileNo { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
