//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHSForm.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAlert
    {
        public int custAID { get; set; }
        public string Message { get; set; }
        public Nullable<int> custATID { get; set; }
        public Nullable<int> custID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> catID { get; set; }
        public Nullable<int> catsubID { get; set; }
        public Nullable<int> vID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerAltersType CustomerAltersType { get; set; }
        public virtual MainCategory MainCategory { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Venture Venture { get; set; }
    }
}
