//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHSForm.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int fileID { get; set; }
        public Nullable<int> uID { get; set; }
        public Nullable<int> suID { get; set; }
        public Nullable<int> stfID { get; set; }
        public Nullable<int> catID { get; set; }
        public Nullable<int> catsubID { get; set; }
        public Nullable<int> servcatID { get; set; }
        public Nullable<int> servsubcatID { get; set; }
        public Nullable<int> stID { get; set; }
        public string Filename { get; set; }
        public string FileContentType { get; set; }
        public string FileFieldName { get; set; }
        public string FileSize { get; set; }
        public Nullable<int> FileUse { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> cuiD { get; set; }
        public Nullable<int> custODID { get; set; }
        public Nullable<int> custSID { get; set; }
    
        public virtual Admin_Sub Admin_Sub { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CustomerOfficalDetail CustomerOfficalDetail { get; set; }
        public virtual FileUse FileUse1 { get; set; }
        public virtual MainCategory MainCategory { get; set; }
        public virtual ServiceCategory ServiceCategory { get; set; }
        public virtual ServiceSubCategory ServiceSubCategory { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Support Support { get; set; }
        public virtual User User { get; set; }
        public virtual CustomerSupport CustomerSupport { get; set; }
    }
}
