//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHSForm.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int id { get; set; }
        public string Username { get; set; }
        public System.DateTime logDate { get; set; }
        public string logThread { get; set; }
        public string logLevel { get; set; }
        public string logSource { get; set; }
        public string logMessage { get; set; }
        public string exception { get; set; }
        public string IPAddress { get; set; }
    }
}
