//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHSForm.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int pID { get; set; }
        public Nullable<int> vID { get; set; }
        public Nullable<int> uID { get; set; }
        public Nullable<int> suID { get; set; }
        public Nullable<int> cuID { get; set; }
        public Nullable<int> PTID { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string Number { get; set; }
        public string PlotNo { get; set; }
        public string PlotArea { get; set; }
        public string Size { get; set; }
        public string PlotStatus { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public Nullable<int> TotalFloors { get; set; }
        public string FloorNo { get; set; }
        public string RentAmount { get; set; }
        public string UseFor { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedRole { get; set; }
        public Nullable<int> UpdatedRole { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Admin_Sub Admin_Sub { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual User User { get; set; }
        public virtual Venture Venture { get; set; }
    }
}
